#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="iogen"
device="iogen"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms

rm -f /dev/${device} 
mknod /dev/${device} c $major 0
echo mknod /dev/${device} c $major 0
#ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}  
chmod $mode  /dev/${device} 
