#Makefile for 104-IIRO-(16/16E) 104-II-16 104-RO-16

default: all

all: sample0
	@echo made all

sample0: sample0.c acceslib.c acceslib.h iogen.h
	cc -o sample0 sample0.c acceslib.c
	@echo made sample0
